format_version: 10
pipelines:
  Test1:
    group: AT20Group
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-89e38d1:
        git: https://github.com/AT20-DevOps/AT20_MEETING_SERVICE.git
        username: GioBlanco
        shallow_clone: false
        auto_update: true
        branch: task10
        encrypted_password: AES:Wey6o299QCHHaHkYbzFuvQ==:AS+IvBKSX61BzsRj4K4b6A==
    stages:
    - Test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          unit-test:
            timeout: 0
            resources:
            - ubuntu
            tasks:
            - script:
                echo hello world
                npm install
                npm test
    - code-inspection:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          sonar:
            timeout: 0
            resources: 
            - ubuntu
            tasks:
            - exec:
                arguments:
                - sonar-scanner command here
                command: echo
                run_if: passed
