format_version: 10
pipelines:
  Test1:
    group: AT20Group
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-d501a0e:
        git: https://github.com/AT20-DevOps/AT20_MEETING_SERVICE.git
        username: LorenaRamirez7
        shallow_clone: false
        auto_update: true
        branch: taskLR-10
        encrypted_password: AES:9szTJ+P0QMW+/2nTqiAd8Q==:e89x0BD7J0icgsfYSKdgVQ==
    stages:
    - Test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          unit-test:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - Hello
                - World
                command: echo
                run_if: passed
          code_coverage:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - -la
                command: ls
                run_if: passed
    - code_inspection:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          sonar:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - sonar-scanner command here
                command: echo
                run_if: passed
