format_version: 10
pipelines:
  Test1:
    group: AT20Group
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    environment_variables:
      GIT_COMMIT_HASH: 1.2
    secure_variables:
      SONAR_TOKEN: AES:5Y+WdbCALNBBhH4RP7heqA==:WOpYrtphrghvSQ3XMOb3SQFJCzMK6rZqjdDfPO1A/s5hfZfGLUqBPVMbjxNWnZC4
      DOCKER_PASS: AES:JamLUpg2O136hJ2Y+W5p/w==:wx1MbsOidSridzB5/KlXwL+VLW3nUE+PjhMhBxuOpxHISu4mHCoNaYzOAwmQG/27
    materials:
      git-89e38d1:
        git: https://github.com/AT20-DevOps/AT20_MEETING_SERVICE.git
        username: GioBlanco
        shallow_clone: false
        auto_update: true
        branch: task11
        encrypted_password: AES:Wey6o299QCHHaHkYbzFuvQ==:AS+IvBKSX61BzsRj4K4b6A==
    stages:
    - Test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          unit-test:
            timeout: 0
            resources:
            - ubuntu
            tasks:
            - script: |
                npm install
                npm test
            artifacts:
            - build:
                source: test-report.html
                destination: html_report
            - build:
                source: Dockerfile
            - build:
                source: .dockerignore
    - code-inspection:
        fetch_materials: false
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          sonar:
            timeout: 0
            resources: 
            - ubuntu
            tasks:
            - fetch:
                is_file: false
                source: node_modules
                stage: Test
                job: unit-test
                run_if: passed
            - script: |
                /godata/.sonar/sonar-scanner-4.7.0.2747-linux/bin/sonar-scanner \
                        -Dsonar.organization=gb-at20 \
                        -Dsonar.projectKey=AT20-GB \
                        -Dsonar.sources=. \
                        -Dsonar.host.url=https://sonarcloud.io
    - PackageAndPublish:
        fetch_materials: false
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          docker:
            timeout: 0
            resources:
            - docker
            tasks:
            - fetch:
                is_file: false
                source: .dockerignore
                stage: Test
                job: unit-test
                run_if: passed
            - fetch:
                is_file: true
                source: Dockerfile
                stage: Test
                job: unit-test
                run_if: passed
            - script: |
                ls -la
                echo docker build -t at20-meeting_service .
                echo docker login -u gioblanco -p ${DOCKER_PASS}
                echo docker tag at20-meeting_service gioblanco/meeting-service:${GIT_COMMIT_HASH}
                echo docker push gioblanco/meeting-service:${GIT_COMMIT_HASH}
